<?php

namespace Macghriogair\Support\Tests;

use Macghriogair\Support\Parser\PropertiesParser;

class PropertiesParserTest extends \PHPUnit\Framework\TestCase
{
    /** @test */
    public function itParsesAJavaStylePropertiesString()
    {
        $text = "#This file is automatically generated - DO NOT EDIT\n#Tue, 03 May 2016 15:23:07 +0200\nbuildtime=03-05-2016 15\:23\nversion=my-php-project.develop\nbuild=78\nbuilder=pmacgregor\nsystem=MINGW32_NT-6.1\n";

        $this->assertEquals(
            PropertiesParser::fromString($text),
            [
                "buildtime" => "03-05-2016 15\:23",
                "version" => "my-php-project.develop",
                "build" => "78",
                "builder" => "pmacgregor",
                "system" => "MINGW32_NT-6.1"
            ]);
    }
}
